name: Bug 报告
description: 提交一个 bug
labels:
  - "P2"
type: Bug

body:
  - type: markdown
    attributes:
      value: |
        欢迎反馈 bug！
        在提交之前，请确保你已经搜索过已有的 issues，确保没有重复问题。
        请尽量提供多的信息，这将帮助问题更快解决。

  - type: textarea
    id: issue-description
    attributes:
      label: 问题描述
      description: 详细描述你遇到的问题，可以附加截图或录屏。
    validations:
      required: false

  - type: textarea
    id: reproduce
    attributes:
      label: 复现步骤
      description: 说明如何让这个问题再次发生，越详细越好。如果不确定如何复现，请留空。
    validations:
      required: false

  - type: input
    id: version-ani
    attributes:
      label: Ani 版本号
      description: 你正在使用的 Ani 版本号，可在 "设置-软件更新" 中找到，如 `4.0.0`。`4.4.0-beta01` 也可以简写为 `440b1`。
      placeholder: "例如: 4.0.0"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: 操作系统
      description: 不选择表示可能均受影响
      multiple: true
      options:
        - Android 手机/平板
        - Windows
        - macOS (M 系列芯片)
        - Ubuntu
        - Android TV
        - macOS (Intel)
    validations:
      required: false

  - type: textarea
    id: logs-system
    attributes:
      label: 应用日志
      description: |
        对于 PC 端用户，在 "设置-关于" 中点击打开日志目录，把 `app.log` 复制拖到这里。
        对于 Android 用户，在 "设置-关于" 中分享日志，可以分享到 Telegram 群内获取链接，或者自行上传到这里或者 pastebin 等网站。
      placeholder: |
        请在拖拽文件到这里，或者粘贴日志 (全部) 内容。
        请同时说明问题的发生时间，最好精确到分钟 (例如 19:43 左右)。
      value: "..."
    validations:
      required: false
